# Generated by Django 6.0.3 on 2026-06-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dui', models.CharField(blank=True, max_length=10)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('tipo_contribuyente', models.CharField(choices=[('empleado', 'Empleado'), ('freelance', 'Freelance'), ('empresa', 'Empresa'), ('otro', 'Otro')], default='empleado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
