# Generated by Django 6.0.3 on 2026-06-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltributario',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfiltributario',
            name='salario_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
