# Generated by Django 6.0.3 on 2026-06-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documentotributario_delete_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_extraido', models.TextField()),
                ('nit_tradicional', models.CharField(blank=True, max_length=20, null=True)),
                ('identificador_homologado', models.CharField(blank=True, max_length=20, null=True)),
                ('montos_detectados', models.TextField(blank=True, null=True)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.documentotributario')),
            ],
        ),
    ]
