# Generated by Django 6.0.3 on 2026-06-14 00:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_analisisdocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisdocumento',
            name='categoria_detectada',
            field=models.CharField(blank=True, default='tributario', max_length=50),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='confianza_clasificacion',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='documentotributario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentotributario',
            name='texto_extraido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentotributario',
            name='tipo_documento',
            field=models.CharField(choices=[('constancia_salarial', 'Constancia Salarial'), ('declaracion_renta', 'Declaración de Renta'), ('comprobante_retension', 'Comprobante de Retención'), ('factura', 'Factura'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='analisisdocumento',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='core.documentotributario'),
        ),
        migrations.AlterField(
            model_name='documentotributario',
            name='archivo',
            field=models.FileField(upload_to='documentos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='documentotributario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('analizado', 'Analizado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentotributario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConversacionAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva conversación', max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizada_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente')], max_length=10)),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversacionasistente')),
                ('documentos_referenciados', models.ManyToManyField(blank=True, related_name='mensajes_relacionados', to='core.documentotributario')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
    ]
