# Generated by Django 6.0.3 on 2026-06-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_analisisdocumento_iva_analisisdocumento_otros_cargos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisdocumento',
            name='recomendacion_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
