# Generated by Django 6.0.3 on 2026-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_analisisdocumento_recomendacion_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisdocumento',
            name='direccion_detectada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='fecha_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='resumen_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='tipo_documento_detectado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
