# Generated by Django 6.0.3 on 2026-06-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_analisisdocumento_direccion_detectada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisdocumento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='entidades_detectadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='palabras_extraidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analisisdocumento',
            name='direccion_detectada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
