# Generated by Django 6.0.3 on 2026-06-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_analisisdocumento_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisdocumento',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='giro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='nrc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
