# Generated by Django 6.0.3 on 2026-06-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_analisisdocumento_correo_analisisdocumento_giro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisdocumento',
            name='es_deducible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='es_documento_tributario',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='justificacion_deducible',
            field=models.TextField(blank=True, null=True),
        ),
    ]
