# Generated by Django 6.0.3 on 2026-06-17 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_analisisdocumento_es_deducible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio'), ('factura', 'Factura'), ('vencimiento', 'Vencimiento')], default='recordatorio', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'creado_en'],
            },
        ),
    ]
