# Generated by Django 6.0.7 on 2026-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_eventocalendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('identificador', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('cubeta', models.PositiveBigIntegerField()),
                ('contador', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
