# Generated by Django 6.0.7 on 2026-08-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ratelimitbucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisdocumento',
            name='feedback_comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='feedback_usuario',
            field=models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=10, null=True),
        ),
    ]
