# Generated by Django 6.0.7 on 2026-08-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_usogemini'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisdocumento',
            name='modelo_ia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
